---
deployment:
  tasks:
    - export DEPLOYPATH=/home/durratiz/public_html/
    - /bin/rm -rf $DEPLOYPATH/*
    - /usr/local/bin/npm install
    - /usr/local/bin/npm run build
    - /usr/local/bin/npm run export
    - /bin/cp -R out/* $DEPLOYPATH
