---
deployment:
  tasks:
    - export DEPLOYPATH=/home/durratiz/repositories/durrat
    - /bin/cp -R * $DEPLOYPATH/
    - cd $DEPLOYPATH && npm install --production
    - cd $DEPLOYPATH && npm run build
    - /opt/cpanel/ea-nodejs18/bin/pm2 restart server.js || true
