---
deployment:
  tasks:
   - |
      source /home/durratiz/nodevenv/repositories/durrat/18/bin/activate
      npm install --production
   - |
      source /home/durratiz/nodevenv/repositories/durrat/18/bin/activate
      npx pm2 restart server.js || npx pm2 start server.js --name "durrat"