---
deployment:
  tasks:
    - export DEPLOYPATH=/home/durratiz/public_html/
    - /bin/rm -rf $DEPLOYPATH/*
    - cd /home/durratiz/repositories/durrat  
    - npm install
    - npm run build
    - /bin/cp -R .next $DEPLOYPATH
    - /bin/cp -R public/* $DEPLOYPATH/public