---
deployment:
  tasks:
    - export PATH=/opt/cpanel/ea-nodejs18/bin:$PATH
    - npm install --scripts-prepend-node-path
    - npm run build
    - /opt/cpanel/ea-nodejs18/bin/pm2 restart server.js || /opt/cpanel/ea-nodejs18/bin/pm2 start server.js --name "durrat"