---
deployment:
  tasks:
    - |
      /opt/cpanel/ea-nodejs18/bin/npm install --scripts-prepend-node-path
      /opt/cpanel/ea-nodejs18/bin/npm run build
    - /opt/cpanel/ea-nodejs18/bin/pm2 restart server.js || /opt/cpanel/ea-nodejs18/bin/pm2 start server.js --name "durrat"